version: "3"
services: 
  node_dev_env:
    image: node:latest
    working_dir: /home/app
    container_name: node-docker
    ports: 
      - 3000:3000
    volumes: 
      - ./:/home/app
    command: sh -c "npm install && npm start"